=== mskcc/fp-docker/inst/data/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "watcher_dir": {
      "type": "string"
    },
    "verify_sshfs_mount": {
      "type": "string"
    },
    "r_script_path": {
      "type": "string"
    },
    "facets_suite_lib": {
      "type": "string"
    },
    "facets_suite_run_wrapper": {
      "type": "string"
    },
    "facets_qc_script": {
      "type": "string"
    },    
    "repo": {
      "type": "array",
      "items": { "$ref": "#/definitions/repository" },
       "minItems": 1
    },
    "facets_lib": {
      "type": "array",
      "items": { "$ref": "#/definitions/rlib" },
       "minItems": 1
    }
  },
  "definitions" : {
    "repository" : {
      "type" : "object",
      "required" : ["name", "manifest_file", "counts_file_format"],
      "properties" : {
        "name" : {
          "type": "string"
        },
        "manifest_file": {
          "type": "string"
        },
        "tumor_id_format": {
          "type": "string"
        },
        "counts_file_format": {
          "type": "string"
        }
      }
    },
    "rlib" : {
      "type" : "object",
      "required" : ["version", "lib_path"],
      "properties" : {
        "version" : {
          "type": "string"
        },
        "lib_path": {
          "type": "string"
        }
      }      
    }
  },
  "required": [ "watcher_dir", "verify_sshfs_mount", "r_script_path", "facets_suite_lib", "facets_suite_run_wrapper", "facets_qc_script", "facets_lib", "repo"]
}

=== mskcc/fp-docker/Docker/impact_juno_config.json
{
	"repo": [
		{
			"name": "Clinical series IMPACT",
			"manifest_file": "/juno/work/ccs/shared/resources/impact/facets/manifests/impact_facets_manifest_latest.txt.gz",
			"tumor_id_format": "^P-\\d{7}-T\\d+-IM\\d(,P-\\d{7}-T\\d+-IM\\d)*$",
			"counts_file_format": "countsMerged____{sample_id}.dat.gz"
	        }
	],
	"watcher_dir": "/juno/work/ccs/shared/software/refit_watcher/",
	"facets_lib": [
		{
			"version": "0.5.14",
			"lib_path": "/usr/local/lib/R/site-library/facets/"
		}
	],
	"verify_sshfs_mount" : "",
	"r_script_path" : "/usr/local/bin/Rscript",
	"facets_suite_lib": "/usr/local/lib/R/site-library/",
	"facets_suite_run_wrapper": "/usr/bin/facets-suite/run-facets-wrapper.R",
	"facets_qc_script": "/usr/bin/facets-preview/facets_qc/v1.0/facets_fit_qc.R"
}

=== mskcc/fp-docker/example_facets_preview.json
{
  "repo": [
    {
      "name": "CCS IMPACT facets repository",
      "manifest_file": "/juno/work/ccs/shared/resources/impact/facets/manifests/impact_facets_manifest_latest.txt.gz",
      "tumor_id_format": "^P-\\d{7}-T\\d+-IM\\d(,P-\\d{7}-T\\d+-IM\\d)*$",
      "counts_file_format": "countsMerged____{sample_id}.dat.gz"
    },
    {
      "name": "CB Test Repo",
      "manifest_file": "/juno/work/ccs/bandlamc/other_stuff/facets_qc/facets_sandbox/manifests/impact_facets_qc_2020_02_17b.txt.gz",
      "tumor_id_format": "",
      "counts_file_format": "countsMerged____{sample_id}.dat.gz"
    }
  ],
  "watcher_dir": "/juno/work/ccs/shared/software/refit_watcher/",
  "facets_lib": [
    {
      "version": "0.5.6",
      "lib_path": "/juno/work/ccs/shared/software/R_libs/facets/0.5.6/"
    },
    {
      "version": "0.5.14",
      "lib_path": "/juno/work/ccs/shared/software/R_libs/facets/0.5.14/"
    },
    {
      "version": "0.6.0",
      "lib_path": "/juno/work/ccs/shared/software/R_libs/facets/0.6.0/"
    }
  ],
  "verify_sshfs_mount" : "juno",
  "r_script_path" : "/opt/common/CentOS_7-dev/bin/Rscript",
  "facets_suite_lib": "/juno/work/ccs/shared/software/R_libs/facetsSuite/2.0.8/",
  "facets_suite_run_wrapper": "/juno/work/ccs/shared/software/R_libs/facetsSuite/2.0.6/run-facets-wrapper.R",
  "facets_qc_script": "/juno/work/ccs/bandlamc/git/facets-preview/facets_qc/v1.0/facets_fit_qc.R"
}

=== mskcc/fp-docker/Docker/fp_config.json
{
  "repo": [
    {
      "name": "Tempo",
      "manifest_file": "/Users/noronhaa/Documents/facets_img_test/manifest.txt.gz",
      "tumor_id_format": "",
      "counts_file_format": "{sample_id}.snp_pileup.gz"
    }
  ],
  "watcher_dir": "/Users/aprice/mskcc/pipelines/fp-docker/Docker/watcher_dir",
  "facets_lib": [
    {
      "version": "0.5.14",
      "lib_path": "/usr/local/lib/R/site-library/facets/"
    }
  ],
  "verify_sshfs_mount" : "",
  "r_script_path" : "/usr/local/bin/Rscript",
  "facets_suite_lib": "/usr/local/lib/R/site-library/",
  "facets_suite_run_wrapper": "/usr/bin/facets-suite/run-facets-wrapper.R",
  "facets_qc_script": "/usr/bin/facets-preview/facets_qc/v1.0/facets_fit_qc.R"
}
